// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhqPryNZxQaOQI76WivtW_n3r2hzGtKUI',
    appId: '1:548619356231:web:9395a788325a6b859f8962',
    messagingSenderId: '548619356231',
    projectId: 'quran-words-2b4b2',
    authDomain: 'quran-words-2b4b2.firebaseapp.com',
    storageBucket: 'quran-words-2b4b2.firebasestorage.app',
    measurementId: 'G-D8BZL6GHBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEo0_2so0appzjbEGKlRQBlYtOALw1Iz4',
    appId: '1:548619356231:android:1978bb57617af3c49f8962',
    messagingSenderId: '548619356231',
    projectId: 'quran-words-2b4b2',
    storageBucket: 'quran-words-2b4b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBThijtVg98Pv2_biCq5tzQNZ9kq12YXP4',
    appId: '1:548619356231:ios:d6e9dfb40ba7cb6c9f8962',
    messagingSenderId: '548619356231',
    projectId: 'quran-words-2b4b2',
    storageBucket: 'quran-words-2b4b2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTestQuran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBThijtVg98Pv2_biCq5tzQNZ9kq12YXP4',
    appId: '1:548619356231:ios:d6e9dfb40ba7cb6c9f8962',
    messagingSenderId: '548619356231',
    projectId: 'quran-words-2b4b2',
    storageBucket: 'quran-words-2b4b2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTestQuran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhqPryNZxQaOQI76WivtW_n3r2hzGtKUI',
    appId: '1:548619356231:web:a831d5e7b582824c9f8962',
    messagingSenderId: '548619356231',
    projectId: 'quran-words-2b4b2',
    authDomain: 'quran-words-2b4b2.firebaseapp.com',
    storageBucket: 'quran-words-2b4b2.firebasestorage.app',
    measurementId: 'G-NE4RN38MKY',
  );
}
